version: '3.7'
services:
  wordpress:
    image: wordpress:5.4.0-fpm
    restart: always
    networks:
      - wordpress
    volumes:
      - wordpress-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database
      MYSQL_ROOT_PASSWORD: RootSecret
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: UserSecret
      WORDPRESS_TABLE_PREFIX: wp_
    depends_on:
      - database
  database:
    image: mariadb:10.4.12-bionic
    restart: always
    networks:
      - wordpress
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: RootSecret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: UserSecret
  nginx:
    image: nginx
    restart: always
    networks:
      - wordpress
    ports:
      - 6080:80
      - 60443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-data:/usr/share/nginx/html
    depends_on:
      - wordpress
volumes:
  wordpress-data:
  database-data:
  nginx-data:

networks:
  wordpress:
    driver: bridge
    name: wordpress
