version: '3.7'
services:
  wordpress:
    image: wordpress:5.4.0-fpm
    restart: always
    networks:
      - wordpress
    volumes:
      - wordpress-data:/var/www/html
      - ./wp-plugins/amazon-s3-and-cloudfront.2.3.2:/var/www/html/wp-content/plugins/amazon-s3-and-cloudfront
    environment:
      WORDPRESS_DB_HOST: database
      MYSQL_ROOT_PASSWORD: RootSecret
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: UserSecret
      WORDPRESS_TABLE_PREFIX: wp_
    depends_on:
      - database
  database:
    image: mariadb:10.4.12-bionic
    restart: always
    networks:
      - wordpress
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: RootSecret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: UserSecret
  nginx:
    image: nginx
    restart: always
    networks:
      - wordpress
    ports:
      - 6080:80
      - 60443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress-data:/var/www/html
      - nginx-data:/usr/share/nginx/html
    depends_on:
      - wordpress
  minio:
    image: minio/minio
    command: "server /data"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ACCESS_KEY: AdminAccessKey
      MINIO_SECRET_KEY: AdminSecretKey
    ports:
      - "6090:9000"
  memcached:
    image: memcached
    command: memcached -m 32
      
volumes:
  wordpress-data:
  database-data:
  nginx-data:
  minio-data:

networks:
  wordpress:
    driver: bridge
    name: wordpress
